# **1.배열**

* 데이터를 나열하고 각 데이터를 인덱스에 대응하도록 구성한 자료구조
* 파이썬에서는 리스트 타입이 배열 기능을 제공함

### **1-1. 배열이 필요한 이유**

* 같은 종류의 데이터를 효율적으로 관리하기 위해 사용
* 같은 종류의 데이터를 순차적으로 저장
* 빠른 접근이 가능(인덱스 번호로 접근)

### **1-2. 배열의 단점**

* 데이터의 추가 / 삭제가 어려움
* 미리 최대 길이를 설정해야 함

In [9]:
# 1차원 배열 : 리스트로 구현
arr_list = [1,2,3,4,5]
print(arr_list)

[1, 2, 3, 4, 5]

In [13]:
arr_list = [[1,2,3],[4,5,6],[7,8,9]]
print(arr_list)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
print(arr_list[0])
print(arr_list[0][0])

[1, 2, 3]
1

### **문제**

위 2차원 배열에서 값을 9 8 7 순서로 출력해보자

In [21]:
print(arr_list[2][-1],arr_list[2][-2],arr_list[2][-3])

9 8 7

### **문제-2**

dataset 리스트에서 전체 이름안에 'M'은 몇번 나왔는지 빈도수를 출력해보자

In [24]:
dataset = ['Braund, Mr. Owen Harris',
'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
'Heikkinen, Miss. Laina',
'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
'Allen, Mr. William Henry',
'Moran, Mr. James',
'McCarthy, Mr. Timothy J',
'Palsson, Master. Gosta Leonard',
'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
'Nasser, Mrs. Nicholas (Adele Achem)',
'Sandstrom, Miss. Marguerite Rut',
'Bonnell, Miss. Elizabeth',
'Saundercock, Mr. William Henry',
'Andersson, Mr. Anders Johan',
'Vestrom, Miss. Hulda Amanda Adolfina',
'Hewlett, Mrs. (Mary D Kingcome) ',
'Rice, Master. Eugene','Williams, Mr. Charles Eugene',
'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
'Masselmani, Mrs. Fatima',
'Fynney, Mr. Joseph J',
'Beesley, Mr. Lawrence',
'McGowan, Miss. Anna "Annie"',
'Sloper, Mr. William Thompson',
'Palsson, Miss. Torborg Danira',
'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
'Emir, Mr. Farred Chehab',
'Fortune, Mr. Charles Alexander',
'Dwyer, Miss. Ellen "Nellie"',
'Todoroff, Mr. Lalio']

In [47]:
cnt = 0

for data in (dataset):
  for index in range(len(data)):
    if data[index] == "M":
      cnt += 1
      # break;

print(cnt)

30

In [58]:
cnt = 0
for data in dataset:
  # print(data)
  for index in range(len(data)):
    if data[index] == "M":
      cnt += 1
    # print(data[index])
  # break;
print(cnt)

38